import wx
application = wx.App()
title1 = wx.Frame(None, title = "collect two numbers")
sizer = wx.BoxSizer(wx.VERTICAL)
def english ():
    gide_label1 = wx.StaticText(title1, label = "please enter your first number")
    sizer.Add(gide_label1, 0, wx.ALL, 5)
    input_user1 = wx.TextCtrl(title1)
    sizer.Add(input_user1, 0, wx.ALL, 5)
    button1 = wx.Button(title1, label = "confirm")
    def data(event):
        user_data1 = input_user1.GetValue()
    button1.Bind(wx.EVT_BUTTON, data)
    sizer.Add(button1, 0, wx.ALL, 5)
    gide_label2 = wx.StaticText(title1, label = "please enter your second number")
    sizer.Add(gide_label2, 0, wx.ALL, 5)
    input_user2 = wx.TextCtrl(title1)
    sizer.Add(input_user2, 0, wx.ALL, 5)
    button2 = wx.Button(title1, label = "input has been received")
    def data1(event):
        user_data1 = input_user1.GetValue()
        user_data2 = input_user2.GetValue()
        result = int(user_data1) + int(user_data2)
        label_result = wx.StaticText(title1, label = str(result))
        sizer.Add(label_result, 0, wx.ALL, 5)
    button2.Bind(wx.EVT_BUTTON, data1)
    sizer.Add(button2, 0, wx.ALL, 5)
def persian():
    gide_label1 = wx.StaticText(title1, label = "لطفاً عدد اول خود را وارد کنید")
    sizer.Add(gide_label1, 0, wx.ALL, 5)
    input_user1 = wx.TextCtrl(title1)
    sizer.Add(input_user1, 0, wx.ALL, 5)
    button1 = wx.Button(title1, label = "تأیید")
    def data(event):
        user_data1 = input_user1.GetValue()
    button1.Bind(wx.EVT_BUTTON, data)
    sizer.Add(button1, 0, wx.ALL, 5)
    gide_label2 = wx.StaticText(title1, label = "لطفاً عدد دوم خود را وارد کنید")
    sizer.Add(gide_label2, 0, wx.ALL, 5)
    input_user2 = wx.TextCtrl(title1)
    sizer.Add(input_user2, 0, wx.ALL, 5)
    button2  = wx.Button(title1, label = "ورودی دریافت شد")
    def data1(event):
        user_data1 = input_user1.GetValue()
        user_data2 = input_user2.GetValue()
        result = int(user_data1) + int(user_data2)
        label_result = wx.StaticText(title1, label = str(result))
        sizer.Add(label_result, 0, wx.ALL, 5)
    button2.Bind(wx.EVT_BUTTON, data1)
    sizer.Add(button2, 0, wx.ALL, 5)
def language_selecter(english, persian):
    gide_label = wx.StaticText(title1, label = "enter your desired language, type en or english for english, pe or persian for persian")
    sizer.Add(gide_label, 0, wx.ALL, 5)
    input_user = wx.TextCtrl(title1)
    sizer.Add(input_user, 0, wx.ALL, 5)
    button0 = wx.Button(title1, label = "language")
    def language(event):
        user_data = input_user.GetValue()
        if user_data.lower().strip() == "en" or user_data.lower().strip() == "english":
            wx.MessageBox("language set successfully")
            return english()
        elif user_data.lower().strip() == "pe" or user_data.lower().strip() == "persian":
            wx.MessageBox("زبان با موفقیت تنظیم شد")
            return persian()
    button0.Bind(wx.EVT_BUTTON, language)
    sizer.Add(button0, 0, wx.ALL, 5)
language_selecter(english, persian)
title1.SetSizer(sizer)
title1.Layout()
title1.Show()
application.MainLoop()